Pix 29 Проработать визуальную часть игры
vairaden/pixel-punch-game pull request #18
Opened 2024-02-25 19:01 UTC by Muhozhukov

### Какую задачу решаем
Кружки и прямоугольники заменены на 2д модели. 
Сформированы спрайты для героя, противников, базы и заднего фона. 
Настроена анимация для передвижения героя и противников, анимация атаки противников. 
Создан отдельный класс для работы со спрайтами, а также класс для работы с загрузкой ресурсов

### Скриншоты/видяшка (если есть)

https://github.com/vairaden/pixel-punch-game/assets/65251313/d8290f16-bb80-4b50-8831-d9849363ce18

### TBD (если есть)

2024-02-26 15:26 UTC, BorshevVladimir commented on packages/client/src/processes/GameProcess/index.ts
> +export { GameProcess } from './GameProcess';
У нас образовалась путаница с форматированием кода в нескольких файлах. Возможно есть еще и другие файлы. Я бы предложил не включать в этот PR такие файлы, у которых поменялось только форматирование. Можно это сделать потом в отдельном PR и исправлениями на неделе доработок. А в этом оставить только то, что касается самой задачи.

2024-02-26 17:06 UTC, Muhozhukov commented on packages/client/src/processes/GameProcess/index.ts
> +export { GameProcess } from './GameProcess';
У меня форматирование во время коммита само происходит. Хук настроен, он запускает по очереди prettier и eslint.

2024-02-26 22:12 UTC, Marina-Golovanova approved these changes

2024-02-26 22:12 UTC, Marina-Golovanova commented on packages/client/src/widgets/Game/Game.tsx
> +    console.log(wrapperRef.current?.offsetWidth);
скорее всего лишний console.log

2024-02-27 10:03 UTC, kate-lozovaya requested changes
Есть комментарий от коллеги про console.log, его лучше убрать. Можно в линтер правило добавить, которое запрещает их.
И оставила несколько своих комментариев. Посмотри их, и призывай меня к ревью еще раз

2024-02-28 08:57 UTC, kate-lozovaya reviewed
Оставила еще один комментарий. Нужно переписать на тернарный оператор условие. 
Еще у меня нет кнопки resolve, поэтому если прошлые комментарии не зарезолвлены и тебе это мешает, порезолви их самомстоятельно

2024-02-28 08:57 UTC, kate-lozovaya commented on packages/client/src/widgets/Game/logic/ResourceManager.ts
>      }
[Исправление]
Почти всегда можно обойтись без let. Тут хорошо подойдет тернарный оператор, можно без спреда.
Еще условия с отрицанием читаются сложнее, чем без них, поэтому если можно без него написать условие, то лучше так и поступить
```ts
const resources = Array.isArray(img) ? img : [img];
```

2024-02-28 16:39 UTC, kate-lozovaya approved these changes
👍🏻

2024-02-28 17:15 UTC, merged