Переключение тем (клиентская часть)
vairaden/pixel-punch-game pull request #38
Opened 2024-04-07 00:36 UTC by vairaden

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-04-07 19:18 UTC, Marina-Golovanova commented on package.json
> +    "dev:server": "cd ./packages/server && npm run dev",
можно откатить к тому, что было: "dev:server": "lerna run dev --scope=server",

2024-04-07 19:19 UTC, Marina-Golovanova approved these changes

2024-04-07 20:04 UTC, Olegas commented on packages/server/src/models/theme.model.ts
> +type TopicCreationAttributes = Optional<ThemeAttributes, 'id'>;
Тут явно опечатка. В файле речь про темы, и тут затесался топик.

2024-04-07 20:06 UTC, Olegas commented on packages/server/src/models/theme.model.ts
> +    user_id: {
На это поле нужен индекс. Индекс должен быть уникальный. Если не сделать его уникальным то при конкурентных запросах в базе может оказаться несколько записей для одного пользователя.

2024-04-07 20:08 UTC, Olegas commented on packages/server/src/controllers/user.controller.ts
> +    const theme = await Theme.findOne({ where: { user_id: id } });
Это лучше сделать за одно обращение - используйте https://sequelize.org/docs/v6/core-concepts/model-querying-finders/#findorcreate

2024-04-07 20:10 UTC, Olegas commented on packages/server/src/controllers/user.controller.ts
> +      if (themeRecord.user_id !== res.locals.user.id) {
А зачем эта проверка? Ведь тут же выше поиск идет сразу по id, который взят из locals

2024-04-07 20:10 UTC, Olegas requested changes
Добрый день. В реализации есть ошибки. Написал подробно в комментариях

2024-04-08 16:41 UTC, Olegas approved these changes
Работа принята

2024-04-08 20:45 UTC, merged