PIX-16 Реализовать логику авторизации
vairaden/pixel-punch-game pull request #5
Opened 2024-02-13 18:11 UTC by Marina-Golovanova

### Какую задачу решаем
PIX-16 Реализовать логику авторизации

### TBD (если есть)
Добавить редирект для неавторизованных пользователей

2024-02-13 18:57 UTC, vairaden commented on packages/client/src/shared/api/authApi.ts
> +    baseUrl: 'https://ya-praktikum.tech/api/v2/auth',
Начало юрал нужно вынести в baseApi, а тут оставить
`/auth`

2024-02-13 18:57 UTC, vairaden commented on packages/client/src/shared/api/baseApi.ts
export const axiosInstance = axios.create({
 baseURL: 'https://ya-praktikum.tech/api/v2'

2024-02-14 11:18 UTC, Muhozhukov commented on packages/client/src/shared/types.ts
> +export type IUser = {
Почему название через I? 
IUser, ILoginData

2024-02-15 09:15 UTC, Muhozhukov submitted a review, later dismissed

2024-02-15 09:28 UTC, berdiyev7 requested changes

2024-02-15 09:29 UTC, berdiyev7 submitted a review, later dismissed

2024-02-15 21:54 UTC, Marina-Golovanova commented on packages/client/src/pages/LoginPage/LoginPage.tsx
>    const onSubmit = (data: FieldValues) => {
вот тут без типа не может разобраться, в остальных местах поправила

2024-02-16 05:39 UTC, Olegas requested changes
Добрый день.
Есть несколько замечаний по коду - нужно доработать
Оставил комментарии в коде в проблемных местах

2024-02-16 05:39 UTC, Olegas commented on packages/client/src/app/providers/router/AuthGuard.tsx
> +  }, []);
Судя по названию этот компонент призван закрыть часть контента для неавторизованного пользователя. Но получается что пока идет запрос за данными пользователя, защищаемый компонент показывается. Вижу в этом проблему.

2024-02-16 05:39 UTC, Olegas commented on packages/client/src/app/providers/router/routes.tsx
> +      </AuthGuard>
А зачем страницу ошибки закрывать авторизацией?

2024-02-16 05:39 UTC, Olegas commented on packages/client/src/app/providers/router/routes.tsx
> +      <AuthGuard>
Тот же вопрос что и про ошибку 500

2024-02-17 11:34 UTC, Olegas approved these changes
Спасибо, работа принята

2024-02-18 00:27 UTC, merged